BEGIN
  -- Lista de comandos ALTER TABLE
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_GL_CODE_COMBINATION NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_COST_CENTER NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_LEGAL_ENTITY NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_NATURAL_ACCOUNT NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_FILIAL_EMPRESA NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_UNID_RESULT NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_JOURNAL MODIFY (ID_CONTRATO NUMBER(12))';
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_LEGAL_ENTITY NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_CODE_COMBINATION NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_COST_CENTER NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_NATURAL_ACCOUNT NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_FILIAL_EMPRESA NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_UNID_RESULT NUMBER(12))';
  EXECUTE IMMEDIATE 'ALTER TABLE FSFINAN.PR_GL_BALANCE MODIFY (ID_CONTRATO NUMBER(12))';
END;
/
