SELECT 
C.PROJECT_ID,
C.TASK_ID,
C.PRVDR_GL_PERIOD_NAME,
C.UOM_CODE,
C.PROJECT_CURRENCY_CODE,
C.QUANTITY,
C.PROJECT_RAW_COST,
C.GLOBAL_RAW_COST,
D.PROJECT_NUMBER
 FROM DW_PROJECT_COST_AGG_CF C
 LEFT JOIN DW_PROJECT_D D
 ON C.PROJECT_ID = D.PROJECT_ID

