
-- Query para verificar duplicações em DMPROJ
SELECT ID_PROJECT, NO_PROJECT_ID, COUNT(*)
FROM FSCORP.DM_PROJECT
GROUP BY ID_PROJECT, NO_PROJECT_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMINTORG
SELECT ID_INTERNAL_ORG, NO_ORGANIZATION_ID, COUNT(*)
FROM FSCORP.DM_INTERNAL_ORG
GROUP BY ID_INTERNAL_ORG, NO_ORGANIZATION_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMPROJEL
SELECT ID_PROJECT_ELEMENT, NO_PROJ_ELEMENT_ID, COUNT(*)
FROM FSCORP.DM_PROJECT_ELEMENT
GROUP BY ID_PROJECT_ELEMENT, NO_PROJ_ELEMENT_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMINVITEM
SELECT ID_INVENTORY_ITEM, NO_INVENTORY_ITEM_ID, COUNT(*)
FROM FSCORP.DM_INVENTORY_ITEM
GROUP BY ID_INVENTORY_ITEM, NO_INVENTORY_ITEM_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMUS
SELECT ID_USER, DS_USERNAME, COUNT(*)
FROM FSCORP.DM_USER
GROUP BY ID_USER, DS_USERNAME
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMPTY
SELECT ID_PARTY, DS_PARTY_NAME, COUNT(*)
FROM FSCORP.DM_PARTY
GROUP BY ID_PARTY, DS_PARTY_NAME
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMEXPTY
SELECT ID_PROJECT_EXPEDITURE_TYPE, NO_EXPENDITURE_TYPE_ID, COUNT(*)
FROM FSCORP.DM_PROJECT_EXPENDITURE
GROUP BY ID_PROJECT_EXPEDITURE_TYPE, NO_EXPENDITURE_TYPE_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMBU
SELECT ID_BUSINESS_UNIT, NO_BUSINESS_UNIT_ID, COUNT(*)
FROM FSCORP.DM_BUSINESS_UNIT
GROUP BY ID_BUSINESS_UNIT, NO_BUSINESS_UNIT_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMLEG
SELECT ID_LEGAL_ENTITY, NO_LEGAL_ENTITY_ID, COUNT(*)
FROM FSCORP.DM_LEGAL_ENTITY
GROUP BY ID_LEGAL_ENTITY, NO_LEGAL_ENTITY_ID
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMCUR
SELECT ID_CURRENCY_DETAILS, CD_CURRENCY, COUNT(*)
FROM FSCORP.DM_CURRENCY_DETAILS
GROUP BY ID_CURRENCY_DETAILS, CD_CURRENCY
HAVING COUNT(*) > 1;

-- Query para verificar duplicações em DMSUP
SELECT ID_SUPPLIER_SITE, NO_SUPPLIER_SITE_ID, COUNT(*)
FROM FSCORP.DM_SUPPLIER_SITE
GROUP BY ID_SUPPLIER_SITE, NO_SUPPLIER_SITE_ID
HAVING COUNT(*) > 1;
