--Consulta de duplicados na staging PURCHASE_ORDER
SELECT 
   * 
FROM (
    SELECT 
        PURCHASE_ORDER_ID,
        PURCHASE_ORDER_LINE_ID,
        --SOURCE_RECORD_ID,
        COUNT(*)
    FROM 
        "FUSION".DW_PURCHASE_ORDER_CF dpoc 
    GROUP BY 
        PURCHASE_ORDER_ID,
        PURCHASE_ORDER_LINE_ID
        --SOURCE_RECORD_ID
    HAVING 
        COUNT(*) > 1
) t;

--Consulta de duplicados na view source PURCHASE_ORDER
SELECT 
   * 
FROM (
    SELECT 
        PURCHASE_ORDER_ID,
        PURCHASE_ORDER_LINE_ID,
        --SOURCE_RECORD_ID,
        COUNT(*)
    FROM 
        V_BI_DW_PURCHASE_ORDER_CF
    WHERE 
        PURCHASE_ORDER_ID = 12086
    GROUP BY 
        PURCHASE_ORDER_ID,
        PURCHASE_ORDER_LINE_ID
        --SOURCE_RECORD_ID
    HAVING 
        COUNT(*) > 0
) t;

--Consulta de duplicados na fato final PURCHASE_ORDER
SELECT 
    *
FROM (
    SELECT 
        NO_PURCHASE_ORDER_ID,
        NO_PURCHASE_ORDER_LINE_ID,
        --DS_SOURCE_RECORD_ID,
        COUNT(*)
    FROM 
        FSSUPRI.PR_PURCHASE_ORDER
    --WHERE NO_PURCHASE_ORDER_ID = 300000061764768
    GROUP BY 
        NO_PURCHASE_ORDER_ID,
        NO_PURCHASE_ORDER_LINE_ID
       -- DS_SOURCE_RECORD_ID
    HAVING 
        COUNT(*) > 1
) t;


-- Verificar duplicatas na DM_CONTRATO
SELECT 
    CD_GL_SEGMENT AS CHAVE, COUNT(*)
FROM FSCORP.DM_CONTRATO
GROUP BY CD_GL_SEGMENT
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_PERSON
SELECT 
    NO_PERSON_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_PERSON
GROUP BY NO_PERSON_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_PARTY
SELECT 
    NO_PARTY_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_PARTY
GROUP BY NO_PARTY_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_SUPPLIER_SITE
SELECT 
    NO_SUPPLIER_SITE_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_SUPPLIER_SITE
GROUP BY NO_SUPPLIER_SITE_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_INVENTORY_ITEM
SELECT 
    NO_INVENTORY_ITEM_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_INVENTORY_ITEM
GROUP BY NO_INVENTORY_ITEM_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_WORKER_LOCATION
SELECT 
    NO_LOCATION_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_WORKER_LOCATION
GROUP BY NO_LOCATION_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_INV_ORGANIZATION
SELECT 
    NO_INV_ORGANIZATION_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_INV_ORGANIZATION
GROUP BY NO_INV_ORGANIZATION_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_PROJECT
SELECT 
    NO_PROJECT_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_PROJECT
GROUP BY NO_PROJECT_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_PROJECT_TASK_HIERARCHY
SELECT 
    NO_BASE_ELEMENT_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_PROJECT_TASK_HIERARCHY
GROUP BY NO_BASE_ELEMENT_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_PROJECT_EXPENDITURE
SELECT 
    NO_EXPENDITURE_TYPE_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_PROJECT_EXPENDITURE
GROUP BY NO_EXPENDITURE_TYPE_ID
HAVING COUNT(*) > 1;

-- Verificar duplicatas na DM_LEGAL_ENTITY
SELECT 
    NO_LEGAL_ENTITY_ID AS CHAVE, COUNT(*)
FROM FSCORP.DM_LEGAL_ENTITY
GROUP BY NO_LEGAL_ENTITY_ID
HAVING COUNT(*) > 1;