WITH
    DMINTORG AS (
	SELECT
		/*+ MATERIALIZE */
		ID_INTERNAL_ORG,
		NO_ORGANIZATION_ID AS PK_JOIN2
	FROM
		FSCORP.DM_INTERNAL_ORG
    ),
    DMLEG AS (
	SELECT
		/*+ MATERIALIZE */
		ID_LEGAL_ENTITY,
		NO_LEGAL_ENTITY_ID AS PK_JOIN2
	FROM
		FSCORP.DM_LEGAL_ENTITY
    )
SELECT SRC.INVOICE_ID, DMLEG.ID_LEGAL_ENTITY --ORG_PAYABLES.ID_INTERNAL_ORG
FROM "FUSION".DW_INVOICE_SPEND_CF SRC
--LEFT JOIN DMINTORG AS ORG_PAYABLES ON SRC.PAYABLES_BU_ID = ORG_PAYABLES.PK_JOIN2
LEFT JOIN DMLEG ON SRC.LEGAL_ENTITY_ID = DMLEG.PK_JOIN2
