SELECT * FROM
DW_GL_BALANCE_CF 
WHERE LEDGER_ID = 300000004085033
AND CODE_COMBINATION_ID = 300000069375869
AND FISCAL_PERIOD_NAME = 'May-25'

SELECT NO_LEDGER_ID, ID_CODE_COMBINATION, DS_FISCAL_PERIOD_NAME, CD_TRANSACTION_CURRENCY, COUNT(*)
FROM VW_DW_GL_BALANCE
GROUP BY NO_LEDGER_ID, ID_CODE_COMBINATION, DS_FISCAL_PERIOD_NAME, CD_TRANSACTION_CURRENCY
HAVING COUNT(*) > 1

SELECT DISTINCT CODE_COMBINATION_ID FROM (
SELECT LEDGER_ID, CODE_COMBINATION_ID, FISCAL_PERIOD_NAME, TRANSACTION_CURRENCY_CODE
FROM DW_GL_BALANCE_CF) A
WHERE LEDGER_ID  = 300000004085033
AND FISCAL_PERIOD_NAME = 'Jul-25'
AND TRANSACTION_CURRENCY_CODE = 'USD'
GROUP BY LEDGER_ID, CODE_COMBINATION_ID, FISCAL_PERIOD_NAME, TRANSACTION_CURRENCY_CODE
HAVING COUNT(*)> 1


SELECT * FROM DW_GL_CODE_COMBINATION_D dgccd 
WHERE CODE_COMBINATION_ID IN (
13045,
39000,
44706,
44757,
44789,
300000070976263,
44527,
44711,
44696,
46249,
44810,
46109,
44937,
44721,
44763,
143041,
44784,
44588,
44799,
101040,
49092,
44745,
44716,
46089,
46272)


ALTER TABLE 

  SELECT * FROM FSCORP.DM_GL_CODE_COMBINATION dgcc 


-- "FUSION".VW_DW_CST_ITEM_COST source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "FUSION"."VW_DW_CST_ITEM_COST" ("NO_COST_ORG_ID", "NO_COST_BOOK_ID", "ID_INVENTORY_ITEM", "NO_VAL_UNIT_ID", "DT_EFFECTIVE_START", "CD_SOURCE_RECORD_ID", "DT_EFFECTIVE_END", "ID_LEGAL_ENTITY", "ID_INVENTORY_ORG", "NO_COST_PROFILE_ID", "ID_CURRENCY", "ID_GLOBAL_CURRENCY", "NO_GLOBAL_CURRENCY_EXCH_RATE", "NO_UNIT_COST", "NO_GLOBAL_UNIT_COST", "CD_COST_METHOD", "CD_UOM") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH
    DMINVITEM AS (
        SELECT /*+ MATERIALIZE */
            ID_INVENTORY_ITEM,
            NO_INVENTORY_ITEM_ID AS PK_JOIN2
        FROM FSCORP.DM_INVENTORY_ITEM
    ),
    DMLEG AS (
        SELECT /*+ MATERIALIZE */
            ID_LEGAL_ENTITY,
            NO_LEGAL_ENTITY_ID AS PK_JOIN2
        FROM FSCORP.DM_LEGAL_ENTITY
    ),
    DMINVORG AS (
        SELECT /*+ MATERIALIZE */
            ID_INV_ORGANIZATION,
            NO_INV_ORGANIZATION_ID AS PK_JOIN2
        FROM FSCORP.DM_INV_ORGANIZATION
    ),
    DMCUR AS (
        SELECT /*+ MATERIALIZE */
            ID_CURRENCY_DETAILS,
            CD_CURRENCY AS PK_JOIN2
        FROM FSCORP.DM_CURRENCY_DETAILS
    )
SELECT
  COST_ORG_ID AS NO_COST_ORG_ID,
  COST_BOOK_ID AS NO_COST_BOOK_ID,
  NVL(DMINVITEM.ID_INVENTORY_ITEM, -1) AS ID_INVENTORY_ITEM,
  VAL_UNIT_ID AS NO_VAL_UNIT_ID,
  EFFECTIVE_START_DATE AS DT_EFFECTIVE_START,
  SOURCE_RECORD_ID AS CD_SOURCE_RECORD_ID,
  EFFECTIVE_END_DATE AS DT_EFFECTIVE_END,
  NVL(DMLEG.ID_LEGAL_ENTITY, -1) AS ID_LEGAL_ENTITY,
  NVL(DMINVORG.ID_INV_ORGANIZATION, -1) AS ID_INVENTORY_ORG,
  COST_PROFILE_ID AS NO_COST_PROFILE_ID,
  DMCUR.ID_CURRENCY_DETAILS AS ID_CURRENCY,
  GL.ID_CURRENCY_DETAILS AS ID_GLOBAL_CURRENCY,
  GLOBAL_CURRENCY_EXCH_RATE AS NO_GLOBAL_CURRENCY_EXCH_RATE,
  UNIT_COST AS NO_UNIT_COST,
  GLOBAL_UNIT_COST AS NO_GLOBAL_UNIT_COST,
  COST_METHOD_CODE AS CD_COST_METHOD,
  UOM_CODE AS CD_UOM
  --COST_ORG_BOOK_LEDGER_ID AS NO_COST_ORG_BOOK_LEDGER_ID,
  --SCENARIO_ID AS NO_SCENARIO_ID ,
  --FISCAL_PERIOD_SET_NAME AS DS_FISCAL_PERIOD_SET_NAME,
  --FISCAL_PERIOD_TYPE AS DS_FISCAL_PERIOD_TYPE,
  --PUBLISHED_FLAG AS DS_PUBLISHED_FLAG,
  --USED_FLAG AS DS_USED_FLAG
  --COST_ELEMENT_ID AS NO_COST_ELEMENT_ID,
  --EXPENSE_POOL_ID AS NO_EXPENSE_POOL_ID,
  --replace(COST_LEVEL_CODE,'~No Value~') AS CD_COST_LEVEL,
FROM
  FUSION.DW_CST_ITEM_COST_CF
LEFT JOIN DMINVITEM
  ON INVENTORY_ITEM_ID = DMINVITEM.PK_JOIN2
LEFT JOIN DMLEG
  ON LEGAL_ENTITY_ID = DMLEG.PK_JOIN2
LEFT JOIN DMINVORG
  ON INVENTORY_ORG_ID = DMINVORG.PK_JOIN2
LEFT JOIN DMCUR
  ON CURRENCY_CODE = DMCUR.PK_JOIN2
LEFT JOIN DMCUR GL
  ON GLOBAL_CURRENCY_CODE = GL.PK_JOIN2;

  GRANT SELECT ON "FUSION"."VW_DW_CST_ITEM_COST" TO "FSSUPRI";
